#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path
from typing import Dict, Iterable, List


WORD_RE = re.compile(r"[A-Za-z0-9_]+")
CJK_RE = re.compile(r"[\u4e00-\u9fff]")

QUERY_CATEGORY_HINTS = {
    "finished_inspection_process": ["成品查貨流程", "成品查货流程", "尾期查货", "3.3a", "3.3b"],
    "semi_finished_inspection_process": ["半成品查貨流程", "半成品查货流程", "半成品查货", "4.7"],
    "quality_standard": ["品質標準", "品质标准", "aql", "允差", "抽样标准", "抽樣標準"],
    "defect_catalog": ["疵點", "疵点", "缺陷", "打褶问题", "破洞", "污渍", "污漬", "色差"],
    "inspection_guideline": ["产品检查及查货工作指引", "產品檢查及查貨工作指引"],
    "work_guideline": ["品質保證部工作指引", "品质保证部工作指引"],
    "inspection_plan": ["订单查货计划", "訂單查貨計劃", "inspection plan"],
}

OVERVIEW_HINTS = ["哪些", "有哪些", "目录", "目錄", "总览", "總覽", "分类", "分類", "全部", "列表"]

SANITIZE_REPLACEMENTS = [
    (re.compile(r"品\s*質\s*保\s*證\s*部"), "相关部门"),
    (re.compile(r"品\s*质\s*保\s*证\s*部"), "相关部门"),
    (re.compile(r"質\s*量\s*管\s*理\s*部\s*門"), "相关部门"),
    (re.compile(r"质\s*量\s*管\s*理\s*部\s*门"), "相关部门"),
    (re.compile(r"品\s*質\s*管\s*理\s*部\s*門"), "相关部门"),
    (re.compile(r"品\s*质\s*管\s*理\s*部\s*门"), "相关部门"),
    (re.compile(r"品\s*質\s*系\s*統\s*管\s*理\s*部"), "相关部门"),
    (re.compile(r"品\s*质\s*系\s*统\s*管\s*理\s*部"), "相关部门"),
    (re.compile(r"品質保證部"), "相关部门"),
    (re.compile(r"品质保证部"), "相关部门"),
    (re.compile(r"品質系統管理部"), "相关部门"),
    (re.compile(r"品质系统管理部"), "相关部门"),
    (re.compile(r"(?:集團|集团)?品管部"), "相关部门"),
    (re.compile(r"质量管理部门"), "相关部门"),
    (re.compile(r"質量管理部門"), "相关部门"),
    (re.compile(r"本部門"), "相关部门"),
    (re.compile(r"本部门"), "相关部门"),
    (re.compile(r"品牌審款中心"), "相关部门"),
    (re.compile(r"品牌审款中心"), "相关部门"),
    (re.compile(r"中國品牌審批中心"), "相关部门"),
    (re.compile(r"中国品牌审批中心"), "相关部门"),
    (re.compile(r"投資業務發展部"), "相关部门"),
    (re.compile(r"投资业务发展部"), "相关部门"),
    (re.compile(r"相關業務部門"), "相关部门"),
    (re.compile(r"相关业务部门"), "相关部门"),
    (re.compile(r"業務發展部門"), "相关部门"),
    (re.compile(r"业务发展部门"), "相关部门"),
    (re.compile(r"審款部門"), "相关部门"),
    (re.compile(r"审款部门"), "相关部门"),
    (re.compile(r"資料組"), "相关部门"),
    (re.compile(r"资料组"), "相关部门"),
    (re.compile(r"採購組"), "相关部门"),
    (re.compile(r"采购组"), "相关部门"),
    (re.compile(r"採購部"), "相关部门"),
    (re.compile(r"采购部"), "相关部门"),
    (re.compile(r"電貿公司"), "匿名组织"),
    (re.compile(r"电贸公司"), "匿名组织"),
    (re.compile(r"本公司"), "匿名组织"),
    (re.compile(r"本组织"), "匿名组织"),
    (re.compile(r"本組織"), "匿名组织"),
    (re.compile(r"本司"), "匿名组织"),
    (re.compile(r"我司"), "匿名组织"),
    (re.compile(r"某组织"), "匿名组织"),
    (re.compile(r"某組織"), "匿名组织"),
    (re.compile(r"力佳實業"), "匿名组织"),
    (re.compile(r"力佳实业"), "匿名组织"),
    (re.compile(r"力佳"), "匿名组织"),
    (re.compile(r"XX投資"), "匿名组织"),
    (re.compile(r"XX投资"), "匿名组织"),
    (re.compile(r"品誠[^\s\"')<>]*"), "匿名组织"),
    (re.compile(r"品诚[^\s\"')<>]*"), "匿名组织"),
    (re.compile(r"三宏達康[^\s\"')<>]*"), "匿名组织"),
    (re.compile(r"三宏达康[^\s\"')<>]*"), "匿名组织"),
    (re.compile(r"JEANSWEST", re.IGNORECASE), "匿名品牌"),
    (re.compile(r"真維斯"), "匿名品牌"),
    (re.compile(r"真维斯"), "匿名品牌"),
    (re.compile(r"Target", re.IGNORECASE), "匿名品牌"),
    (re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"), "匿名署名"),
    (re.compile(r"https?://[^\s)）]+"), "匿名系统"),
    (re.compile(r"eTDS", re.IGNORECASE), "匿名系统"),
    (re.compile(r"工貿系統"), "匿名系统"),
    (re.compile(r"工贸系统"), "匿名系统"),
    (re.compile(r"貿易管理\s*系統"), "匿名系统"),
    (re.compile(r"贸易管理\s*系统"), "匿名系统"),
    (re.compile(r"(?i)(generated by|created by|powered by|sent from)\s+[^\n。；;]+"), "匿名署名"),
    (re.compile(r"(由|通过|透過).{0,20}(APP|App|app|系统|系統|平台|小程序|公众号|公眾號).{0,20}(生成|產生|产生|发送|發送|导出|匯出|导出)"), "匿名署名"),
    (re.compile(r"[\u4e00-\u9fffA-Za-z0-9（）()·.&-]{2,30}(?:有限公司|有限組織|有限组织|集團|集团|公司)(?![\u4e00-\u9fffA-Za-z0-9])"), "匿名组织"),
]


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip().lower()


def sanitize_text(text: str) -> str:
    sanitized = text or ""
    for pattern, replacement in SANITIZE_REPLACEMENTS:
        sanitized = pattern.sub(replacement, sanitized)
    sanitized = re.sub(r"公\s*司", "匿名组织", sanitized)
    sanitized = re.sub(r"(?<!相关)部\s*門", "相关部门", sanitized)
    sanitized = re.sub(r"(?<!相关)部\s*门", "相关部门", sanitized)
    sanitized = re.sub(r"(匿名组织){2,}", "匿名组织", sanitized)
    sanitized = re.sub(r"(匿名品牌){2,}", "匿名品牌", sanitized)
    sanitized = re.sub(r"(匿名系统){2,}", "匿名系统", sanitized)
    sanitized = re.sub(r"(相关部门){2,}", "相关部门", sanitized)
    return sanitized


def tokenize(text: str) -> List[str]:
    text = normalize(text)
    latin_tokens = WORD_RE.findall(text)
    cjk_chars = CJK_RE.findall(text)
    cjk_bigrams = ["".join(cjk_chars[index : index + 2]) for index in range(len(cjk_chars) - 1)]
    return latin_tokens + cjk_chars + cjk_bigrams


def load_registry(path: Path) -> Dict[str, Dict]:
    records: Dict[str, Dict] = {}
    if not path.exists():
        return records
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                record = json.loads(line)
                records[record["doc_id"]] = record
    return records


def iter_chunks(processed_root: Path) -> Iterable[Dict]:
    for chunk_file in sorted(processed_root.glob("*/chunks.jsonl")):
        with chunk_file.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if line:
                    yield json.loads(line)


def score_text(query_tokens: Counter, text: str, weight: float) -> float:
    if not text:
        return 0.0
    tokens = Counter(tokenize(text))
    score = 0.0
    for token, count in query_tokens.items():
        if token in tokens:
            score += min(count, tokens[token]) * weight
    return score


def is_navigation_chunk(chunk: Dict) -> bool:
    source_path = str(chunk.get("source_path", ""))
    return source_path.endswith("/data_structure.md") or source_path == "references/knowledge_base/data_structure.md"


def path_focus_score(query_tokens: Counter, source_path: str) -> float:
    path = Path(source_path)
    focused_parts = [path.parent.name, path.stem]
    score = 0.0
    for part in focused_parts:
        score += score_text(query_tokens, part, 3.5)
    return score


def has_overview_intent(query: str) -> bool:
    normalized = normalize(query)
    return any(hint in normalized for hint in OVERVIEW_HINTS)


def score_chunk(query: str, query_tokens: Counter, chunk: Dict) -> float:
    navigation_chunk = is_navigation_chunk(chunk)
    overview_intent = has_overview_intent(query)
    heading_weight = 2.0 if navigation_chunk else 4.0
    source_weight = 2.0 if navigation_chunk else 2.5
    text_weight = 0.35 if navigation_chunk else 1.0
    coverage_weight = 1.0 if navigation_chunk else 4.0
    text_phrase_bonus = 2.0 if navigation_chunk else 6.0
    heading_phrase_bonus = 4.0 if navigation_chunk else 8.0

    score = 0.0
    score += score_text(query_tokens, chunk.get("heading", ""), heading_weight)
    score += score_text(query_tokens, chunk.get("source_path", ""), source_weight)
    score += score_text(query_tokens, chunk.get("text", ""), text_weight)
    score += score_text(query_tokens, chunk.get("text", "").split("\n", 1)[0], 4.5)

    query_norm = normalize(query)
    text_norm = normalize(chunk.get("text", ""))
    heading_norm = normalize(chunk.get("heading", ""))
    if query_norm and query_norm in text_norm:
        score += text_phrase_bonus
    if query_norm and query_norm in heading_norm:
        score += heading_phrase_bonus

    query_terms = [token for token in tokenize(query) if len(token) > 1]
    if query_terms:
        matched_terms = sum(1 for token in query_terms if token in tokenize(chunk.get("text", "")))
        coverage = matched_terms / len(query_terms)
        score += coverage * coverage_weight

    location_value = str(chunk.get("location_value", ""))
    if location_value and query_norm and query_norm in normalize(location_value):
        score += 2.0

    if not navigation_chunk:
        score += path_focus_score(query_tokens, str(chunk.get("source_path", "")))
    elif len(query_terms) >= 2:
        # Navigation pages are useful fallbacks, but they should not outrank the
        # concrete defect document when the query is already specific.
        score -= 3.0

    if navigation_chunk and overview_intent:
        score += 18.0

    return score


def detect_query_category(query: str) -> str | None:
    lowered = normalize(query)
    best_category = None
    best_score = 0
    for category, hints in QUERY_CATEGORY_HINTS.items():
        score = sum(1 for hint in hints if hint.lower() in lowered)
        if score > best_score:
            best_category = category
            best_score = score
    return best_category


def make_preview(text: str, limit: int = 240) -> str:
    compact = re.sub(r"\s+", " ", sanitize_text(text)).strip()
    if len(compact) <= limit:
        return compact
    return compact[: limit - 1] + "…"


def search(
    query: str,
    registry: Dict[str, Dict],
    processed_root: Path,
    top_k: int,
    business_category: str | None,
    file_type: str | None,
) -> List[Dict]:
    query_tokens = Counter(tokenize(query))
    query_category = detect_query_category(query)
    if not query_tokens:
        return []

    results: List[Dict] = []
    for chunk in iter_chunks(processed_root):
        record = registry.get(chunk["doc_id"])
        if not record:
            continue
        if business_category and record.get("business_category") != business_category:
            continue
        if file_type and record.get("file_type") != file_type:
            continue

        score = score_chunk(query, query_tokens, chunk)
        if query_category:
            if record.get("business_category") == query_category:
                score += 10.0
            else:
                score -= 2.0
        if score <= 0:
            continue

        results.append(
            {
                "score": round(score, 4),
                "doc_id": chunk["doc_id"],
                "source_path": chunk["source_path"],
                "display_source_path": sanitize_text(chunk["source_path"]),
                "is_navigation": is_navigation_chunk(chunk),
                "business_category": record.get("business_category"),
                "file_type": record.get("file_type"),
                "location_label": chunk.get("location_label"),
                "location_value": sanitize_text(str(chunk.get("location_value", ""))),
                "heading": sanitize_text(str(chunk.get("heading", ""))),
                "preview": make_preview(chunk.get("text", "")),
            }
        )

    results.sort(
        key=lambda item: (
            item["score"],
            not item["is_navigation"],
            -len(item["preview"]),
            item["source_path"],
        ),
        reverse=True,
    )
    return results[:top_k]


def render_text(results: List[Dict]) -> str:
    if not results:
        return "No matches."
    lines = []
    for index, item in enumerate(results, start=1):
        lines.extend(
            [
                f"{index}. score={item['score']}",
                f"   source={item.get('display_source_path', item['source_path'])}",
                f"   type={item['file_type']} category={item['business_category']}",
                f"   location={item['location_label']}:{item['location_value']}",
                f"   heading={item['heading']}",
                f"   preview={item['preview']}",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Retrieve relevant processed chunks for QA.")
    parser.add_argument("--query", required=True, help="User question or retrieval query.")
    parser.add_argument("--top-k", type=int, default=5, help="Number of top chunks to return.")
    parser.add_argument("--category", default=None, help="Optional business category filter.")
    parser.add_argument("--file-type", default=None, help="Optional file type filter.")
    parser.add_argument("--json", action="store_true", help="Print JSON results.")
    args = parser.parse_args()

    skill_root = Path(__file__).resolve().parents[1]
    registry = load_registry(skill_root / "references" / "registry.jsonl")
    results = search(
        query=args.query,
        registry=registry,
        processed_root=skill_root / "references" / "processed",
        top_k=args.top_k,
        business_category=args.category,
        file_type=args.file_type,
    )

    if args.json:
        print(json.dumps(results, ensure_ascii=False, indent=2))
    else:
        print(render_text(results))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
